### ISSUE TITLE
Make Jekyll SEO Tag an "official" Jekyll plugin?

### ISSUE THREAD

**Issue by benbalter** [jekyll/jekyll-seo-tag#1]
After doing significant copy pasta to add some search engine metadata to choosealicense.com over in https://github.com/github/choosealicense.com/pull/300, I realized every time I stand up a new Jekyll site, I basically [copy the `seo.html` include from my personal site](https://github.com/benbalter/benbalter.github.com/blob/master/_includes/seo.html), which feels silly.

Like jekyll-sitemap and jekyll-feed which uses the magic of open source to crowd source a best-of-the-best template, I figured it's simple enough to do the same with an include for SEO metadata (including Twitter cards and open graph tags) and spiked out this tiny Gem, which essentially gemifies the include.

* [What it does, usage, etc.](https://github.com/benbalter/jekyll-seo-tag/blob/master/README.md)
* [The include](https://github.com/benbalter/jekyll-seo-tag/blob/master/lib/template.html)
* [Tiny wrapper](https://github.com/benbalter/jekyll-seo-tag/blob/master/lib/jekyll-seo-tag.rb) to render it as `{% seo %}`

@parkr do you think there's any community interest in seeing this be a community maintained (e.g. Jekyll owned plugin)? Since it's just a template in user land, assuming the render logic is sound, I believe it should be easy enough to add to Pages.

/cc @leereilly because SEO :smile:

**Comment by parkr** [comment]
> do you think there's any community interest in seeing this be a community maintained (e.g. Jekyll owned plugin)?

If it's community-owned, it'll be at the whim of what the community wants, which may expand the functionality of this beyond what you originally envisioned.

> Since it's just a template in user land, assuming the render logic is sound, I believe it should be easy enough to add to Pages.

Looks like the [template is in this repo?](https://github.com/benbalter/jekyll-seo-tag/blob/master/lib/template.html). I'm neck-deep in other Jekyll code atm so let me know if I'm missing something glaring. I bet I am.

**Comment by parkr** [comment]
@benbalter ^

**Comment by benbalter** [comment]
> If it's community-owned, it'll be at the whim of what the community wants, which may expand the functionality of this beyond what you originally envisioned.

@benbalter rules with an iron fist.

> Looks like the template is in this repo?. I'm neck-deep in other Jekyll code atm so let me know if I'm missing something glaring. I bet I am.

**Comment by benbalter** [comment]
It's official!

![screen_shot_2016-02-22_at_3_06_17_pm](https://cloud.githubusercontent.com/assets/282759/13231050/f0f9b452-d975-11e5-99f8-919b3b92e3b8.png)

**Comment by pathawks** [comment]
:tada: Yay :+1:
