### ISSUE TITLE
The name of the site pages without the site name

### ISSUE THREAD

**Issue by penyadap** [jekyll/jekyll-seo-tag#101]
How do I set up a site with a title tag seo Jekyll without including the name of the site

Titla page of my site - mysite.com

for which no title include mysite.com

**Comment by benbalter** [comment]
You can [disable the title output](https://github.com/jekyll/jekyll-seo-tag#disabling-title-output) and render the title yourself.

**Comment by penyadap** [comment]
oke, thankss ben 
Very Helpful..
