### ISSUE TITLE
<meta name="twitter:title"> not included

### ISSUE THREAD

**Issue by k-funk** [jekyll/jekyll-seo-tag#104]
According to the [Twitter Docs](https://dev.twitter.com/cards/types/summary) there should be a `<meta name="twitter:title">` tag, but I don't see that tag anywhere in the source where I'd [expect to see it](https://github.com/jekyll/jekyll-seo-tag/blob/master/lib/template.html#L151), nor in the output.

**Comment by benbalter** [comment]
See https://github.com/jekyll/jekyll-seo-tag/pull/65, specifically https://dev.twitter.com/cards/getting-started#opengraph.

> When the Twitter card processor looks for tags on your page, it first checks for the Twitter property, and if not present, falls back to the supported Open Graph property.

**Comment by k-funk** [comment]
Great! Thanks for the quick response!
