### ISSUE TITLE
Feature request/suggestion: <meta name="twitter:image"> default image

### ISSUE THREAD

**Issue by k-funk** [jekyll/jekyll-seo-tag#105]
I'd like to have <meta name="twitter:image"> default to something in the case that I don't include one on the `page.image`. Maybe this is the `site.logo`, or an additional parameter: `site.twitter.default_image`. Thoughts?

**Comment by benbalter** [comment]
You can do this via front matter defaults. See https://jekyllrb.com/docs/configuration/#front-matter-defaults.

**Comment by k-funk** [comment]
Didn't think about this as a solution, thanks for the tip. I'll use that for now. However, I'd prefer to have default images for each social media (twitter, fb, etc). It's hard to predict how they will display the image, so I'd rather have control over which one is used.

**Comment by benbalter** [comment]
> so I'd rather have control over which one is used.

You can do that as well, also via frontmatter defaults. See https://github.com/jekyll/jekyll-seo-tag#customizing-image-output.
