### ISSUE TITLE
Is it okey that title will be added with description and then write in <title> tag? 

### ISSUE THREAD

**Issue by mlibre** [jekyll/jekyll-seo-tag#107]
I just install plugin and i notice that in rendered(output) `index.html`, in <title> tag, title content was added with `description` variable content with a '-', and placed in <title> tag. is it okey? why?

**Comment by pathawks** [comment]
I'm not sure I understand your question. Are you unhappy with how the title tag is rendered? Would you rather it not include the site description?

You can set the `title` key in a page YAML to be used as the `<title>` instead of the default site name and description.

**Comment by mlibre** [comment]
ok. thanks.
just for more clear. here is my `_config.yml`:
```bash
description: Something...foo
title: title_foo
```
And i set {% seo %} in `index.html`'s <head> tag. and it's my rendered title:
```html
<title> title_foo - Something...foo </title>
```
i fix it by `{% seo title=false %}` and set title with other way. i just interested that is it okey?! or something is wrong. BTW thanks.

**Comment by benbalter** [comment]
This is the intended behavior. On my site for example, the title of the home page is `<title>Ben Balter - Attorney, open source developer, product manager</title>`, rather than say, `Home - Ben Balter`. The idea being that you want those descriptive keywords in the title of your homepage so that searches for, e.g., "Balter open source" would be more likely to return the home page.

**Comment by mlibre** [comment]
i got it. thanks

**Comment by danmindru** [comment]
Hi there,

Would you consider adding an option to disable this behaviour?
 
According to general SEO guidelines:
- the title should be between 50-60 characters
- the description should be between 150-160 characters 

My point is, it's rare that title stays within the 50-60 limit with the appended description.
