### ISSUE TITLE
Liquid syntax error (line 102): Unknown tag 'seo'

### ISSUE THREAD

**Issue by tomasparks** [jekyll/jekyll-seo-tag#113]
```
jekyll build
Configuration file: /home/tom/blog/_config.yml
            Source: /home/tom/blog
       Destination: /home/tom/blog/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Liquid Exception: Liquid syntax error (line 102): Unknown tag 'seo' in /_layouts/default.html
jekyll 3.2.1 | Error:  Liquid syntax error (line 102): Unknown tag 'seo'
```

gemfile:
`gem 'jekyll-seo-tag'`

_config.yml
```
gems:
  - jekyll-seo-tag
```

Using jekyll-seo-tag 2.0.0

**Comment by benbalter** [comment]
@tomasparks can you rebuild your site with the `--verbose` flag? Do you, by chance, have two `gems` keys in your config file? I suspect the plugin isn't being loaded.

**Comment by DirtyF** [comment]
@tomasparks  you have indeed many gems keys in [your config file](https://github.com/tomasparks/website/blob/master/_config.yml#L12), that you can simply list under the same `gems` key:

```yaml
gems:
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-lunr-js-search
  - jekyll-pandoc-multiple-formats

```

**Comment by tomasparks** [comment]
@DirtyF 
that solved my issue :)
