### ISSUE TITLE
jekyll-seo-tag load error

### ISSUE THREAD

**Issue by yonglas** [jekyll/jekyll-seo-tag#114]
I am getting this message ("plugin_manager.rb:28:in `require': cannot load such file -- jekyll-seo-tag (LoadError)") when trying to build website.
the plugin is install as you can see here:
![image](https://cloud.githubusercontent.com/assets/1401159/17837306/d0b3560e-67b8-11e6-8ceb-97c3f6a9bfbc.png)

in config.yml i added this :
gems:
  - jekyll-seo-tag

can you assistance ?

**Comment by pathawks** [comment]
Is your site's source public?

What does the error message look like?

**Comment by yonglas** [comment]
ubuntu@ip-172-31-13-111:~/aa210816/getcloudify.org$ jekyll serve -w
Configuration file: /home/ubuntu/aa210816/getcloudify.org/_config.yml
/home/ubuntu/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/x86_64-linux/continuation.so: warning: callcc is obsolete; use Fiber instead
/home/ubuntu/.rvm/gems/ruby-2.2.0/gems/jekyll-2.4.0/lib/jekyll/plugin_manager.rb:28:in `require': **cannot load such file -- jekyll-seo-tag (LoadError)**
        from /home/ubuntu/.rvm/gems/ruby-2.2.0/gems/jekyll-2.4.0/lib/jekyll/plugin_manager.rb:28:in `block in require_gems'
        from /home/ubuntu/.rvm/gems/ruby-2.2.0/gems/jekyll-2.4.0/lib/jekyll/plugin_manager.rb:26:in `each'
        from /home/ubuntu/.rvm/gems/ruby-2.2.0/gems/jekyll-2.4.0/lib/jekyll/plugin_manager.rb:26:in `require_gems'
        from /home/ubuntu/.rvm/gems/ruby-2.2.0/gems/jekyll-2.4.0/lib/jekyll/plugin_manager.rb:19:in `conscientious_require'
        from /home/ubuntu/.rvm/gems/ruby-2.2.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:74:in `setup'
        from /home/ubuntu/.rvm/gems/ruby-2.2.0/gems/jekyll-2.4.0/lib/jekyll/site.rb:36:in `initialize'
        from /home/ubuntu/.rvm/gems/ruby-2.2.0/gems/jekyll-2.4.0/lib/jekyll/commands/build.rb:28:in `new'
        from /home/ubuntu/.rvm/gems/ruby-2.2.0/gems/jekyll-2.4.0/lib/jekyll/commands/build.rb:28:in `process'
        from /home/ubuntu/.rvm/gems/ruby-2.2.0/gems/jekyll-2.4.0/lib/jekyll/commands/serve.rb:25:in `block (2 levels) in init_with_program'
        from /home/ubuntu/.rvm/gems/ruby-2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `call'
        from /home/ubuntu/.rvm/gems/ruby-2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
        from /home/ubuntu/.rvm/gems/ruby-2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
        from /home/ubuntu/.rvm/gems/ruby-2.2.0/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
        from /home/ubuntu/.rvm/gems/ruby-2.2.0/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
        from /home/ubuntu/.rvm/gems/ruby-2.2.0/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
        from /home/ubuntu/.rvm/gems/ruby-2.2.0/gems/jekyll-2.4.0/bin/jekyll:18:in `<top (required)>'
        from /home/ubuntu/.rvm/gems/ruby-2.2.0/bin/jekyll:23:in `load'
        from /home/ubuntu/.rvm/gems/ruby-2.2.0/bin/jekyll:23:in `<main>'
        from /home/ubuntu/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'

**Comment by benbalter** [comment]
have you tried `bundle exec jekyll serve`?

**Comment by yeshess** [comment]
thanks so much, @benbalter! that did the trick.
