### ISSUE TITLE
{% seo %} in readme needs to be {{ seo}}

### ISSUE THREAD

**Issue by sudopluto** [jekyll/jekyll-seo-tag#115]
the build fails otherwise

**Comment by pathawks** [comment]
Can you provide a bit more detail about the problem you are experiencing?

**Comment by sudopluto** [comment]
After taking a glance at the page source it seems that using {{seo}} allows the page to build but the seo tags aren't added

with {% seo %}
![image](https://cloud.githubusercontent.com/assets/9754192/17916015/803830a2-697d-11e6-99cb-24837bb8769f.png)

**Comment by sudopluto** [comment]
nevermind it was missing in my _config.yml, sorry for wasting time

**Comment by pathawks** [comment]
Glad you got it all sorted :+1:
