### ISSUE TITLE
Customize canonical url

### ISSUE THREAD

**Issue by AleksejDix** [jekyll/jekyll-seo-tag#116]
hi what is the variable for customization in the fronmatter. 
```
canonicalurl: https://foo.bar 
```

**Comment by pathawks** [comment]
The canonical URL is built from the permalink and `site.url` and `site.baseurl`

**Comment by xonic** [comment]
Hi,

currently the canonical URL is always the same URL as the current page. I do have two pages with different URL but same content 
```
Page 1 
  URL: https://site.com/
  canonical: https://site.com/
Page 2 
  URL: https://site.com/keyword/
  canonical: https://site.com/keyword/
```
I need to change the canonical on page 2 so that:
```
Page 1 
  URL: https://site.com/
  canonical: https://site.com/
Page 2 
  URL: https://site.com/keyword/
  canonical: https://site.com/
```
How can I achieve this?

Thanks!

**Comment by pathawks** [comment]
This is not currently possible.

You could redirect from one URL to the other.

**Comment by stanidesis** [comment]
@pathawks would 💘 to re-open this because I need the same functionality (for re-circulating content from other sites with canonical claims).

**Comment by pathawks** [comment]
Publishing syndicated content with a canonical URL pointing back to some original site is certainly a valid use case. I am not sure it fits within the scope of this plugin, but I would encourage you to open a new issue focused on that feature request and state your case :+1:
