### ISSUE TITLE
CDN Support

### ISSUE THREAD

**Issue by k-funk** [jekyll/jekyll-seo-tag#118]
My current build assumes that urls that point to assets are relative URLS, and in the last step, prepends my cdn's domain. However, jekyll-seo-tag prepends site.url even thought I don't want it to.

I understand that some tags need the full url (`og:image`, `ld+json:url`), so I can't just remove `site.url` from my config (besides, other plugins expect it to be there).

Current output:
`<meta property="og:url" content="https://www.example.com/index.html" />`
`<meta property="og:image" content="https://www.example.com/assets/logo.png" />`

Desired output:
`<meta property="og:url" content="https://www.example.com/index.html" />`
`<meta property="og:image" content="/assets/logo.png" />`

What do you think about `site.cdn_url | default: site.url` for tags that point to images? That way people can either use jekyll to generate that cdn host, or set it to empty string if they want to handle it after jekyll runs?

**Comment by benbalter** [comment]
Depending on how complex it is to implement, it may make sense to support both absolute and relative URLs, appending `seo_url` to relative URLs and passing absolute URLs as if (if they begin with `https?://` or not.

**Comment by pathawks** [comment]
> it may make sense to support both absolute and relative URLs

[We do!](https://github.com/jekyll/jekyll-seo-tag/blob/v2.0.0/lib/template.html#L97-L99) :+1:
