### ISSUE TITLE
corrupted seo descriptions

### ISSUE THREAD

**Issue by sarbbottam** [jekyll/jekyll-seo-tag#129]
probably due to

```
{% assign seo_description = seo_description | markdownify | strip_html | strip_newlines | escape_once %}
```

at [jekyll-seo-tag/lib/template.html#L50](https://github.com/jekyll/jekyll-seo-tag/blob/master/lib/template.html#L50)

Adding `normalize_whitespace` filter should resolve the issue.

Related issue https://github.com/jekyll/jekyll/issues/4877

**Comment by pathawks** [comment]
Fixed in #126

Will try to cut a new :gem: for you soon :+1:

**Comment by sarbbottam** [comment]
Awesome looking forward to it. Thanks!

**Comment by sarbbottam** [comment]
@pathawks @benbalter could you please release the next version with the fix? Please let me know if I can be of any help. Thanks!

**Comment by DirtyF** [comment]
@sarbbottam in the meantime you can point the gem source to the git repository in your Gemfile:

`gem 'jekyll-seo-tag', :git => 'https://github.com/jekyll/jekyll-seo-tag.git'`

**Comment by sarbbottam** [comment]
Thanks @DirtyF.

**Comment by pathawks** [comment]
@benbalter It looks like you're the only one with permission to cut a gem for [jekyll-seo-tag](https://rubygems.org/gems/jekyll-seo-tag/). Would you mind adding me and probably also @parkr?
