### ISSUE TITLE
Can image information _config.yml be utilized if not present in front matter?

### ISSUE THREAD

**Issue by sarbbottam** [jekyll/jekyll-seo-tag#130]
>The SEO tag will respect any of the following if included in your site's `_config.yml` (and simply not include them if they're not defined):

>* `title` - Your site's title (e.g., Ben's awesome site, The GitHub Blog, etc.)
>* `description` - A short description (e.g., A blog dedicated to reviewing cat gifs)
>* `url` - The full URL to your site. Note: `site.github.url` will be used by default.
>* `author` - global author information (see below)
>* `twitter:username` - The site's Twitter handle. You'll want to describe it like so:

>The SEO tag will respect the following YAML front matter if included in a post, page, or document:

>* `title` - The title of the post, page, or document
>* `description` - A short description of the page's content
>* `image` - URL to an image associated with the post, page, or document (e.g., `/assets/page-pic.jpg`)
>* `author` - Page-, post-, or document-specific author information (see below)

---

`title`, `description`, `author` if not present in YAML front matter, fallbacks to information available in `_config.yml`. 

Wondering, if `image`  can/should be treated in the same way?

**Comment by DirtyF** [comment]
@sarbbottam You can specify a default image in your config file like this:

```
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      image: /assets/images/default-card.png
```

**Comment by sarbbottam** [comment]
Thanks @DirtyF
