### ISSUE TITLE
Specifying a list of social profiles — usage explanation

### ISSUE THREAD

**Issue by callumflack** [jekyll/jekyll-seo-tag#138]
Can a usage example please be provided for specifying a list of social profiles.

I've tried adding both `social: links:` and just `links:` but neither output anything.

**Comment by benbalter** [comment]
See https://github.com/benbalter/benbalter.github.com/blob/9ec654b952e7229b0db1a6190a8df6f542acb2bc/_config.yml#L11-L19.

**Comment by callumflack** [comment]
Thank you!





On Sat, Oct 29, 2016 at 12:06 AM +1000, "Ben Balter" <notifications@github.com> wrote:












See https://github.com/benbalter/benbalter.github.com/blob/9ec654b952e7229b0db1a6190a8df6f542acb2bc/_config.yml#L11-L19.
