### ISSUE TITLE
Raw tags are not respected when encoding urls

### ISSUE THREAD

**Issue by ChadKeating** [jekyll/jekyll-seo-tag#140]
Raw tags are not respected when encoding urls. 

This is causing problems for me as I am using a client side templating library along side jekyll.

For example in my html file: 
```
{% raw %}
<img src="{{image}}" />
<a href="{{foo}}"></a>
<span class="{{bar}}">{{bar}}</span>
{% endraw %}
```

Is rendered as:
```
<img src="%7B%7Bimage%7D%7D">
<a href="%7B%7Bfoo%7D%7D"></a>
<span class="{{bar}}">{{bar}}</span>
```

Expected:
```
<img src="{{image}}" />
<a href="{{foo}}"></a>
<span class="{{bar}}">{{bar}}</span>
```

**Comment by pathawks** [comment]
This is not an issue with this plugin.

I suspect it is a Markdown converter that is rendering the characters this way, or it might be an edge case with Liquid. Either way, this plugin does not impact the rendering of the `{% raw %}` tag.

Maybe try opening an issue in the Jekyll repo.
