### ISSUE TITLE
Unrecognized seo liquid tag

### ISSUE THREAD

**Issue by if3anyi** [jekyll/jekyll-seo-tag#142]
Apologise if this is in the wrong place. On merge with my gp  branch to master, github pages complains it can not identify my set liquid tag for seo. Reviewed the documentation but can not seem to resolve. 

Any help appreciated.

**Error Below:**
`Your site is having problems building: The tag seo on line 5 in /_layouts/default.html is not a recognized Liquid tag`

**Comment by pathawks** [comment]
Can you provide a link to your repo?

**Comment by if3anyi** [comment]
[Repo](https://github.com/if3anyi/if3anyi.github.io)

**Comment by pathawks** [comment]
It looks like `gems` [is indented too far in your `_config.yml`](https://github.com/if3anyi/if3anyi.github.io/blob/c5783611180c5b2f48ad9afe6d0895254b0989d8/_config.yml#L78-L80) so that it is a child of `owner`.

**Comment by if3anyi** [comment]
@pathawks thank you for assisting. That resolved the issue.
