### ISSUE TITLE
Includes Footnote Text

### ISSUE THREAD

**Issue by IanMitchell** [jekyll/jekyll-seo-tag#144]
If you have a sentence with a footnote that's included in the SEO tag, the entire footnote is part of the SEO generation. I don't know if this is intended behavior or not, but it feels like it shouldn't be

**Comment by benbalter** [comment]
> part of the SEO generation

@IanMitchell can you provide an example of how someone might be able to recreate this? I'm afraid I don't follow your explanation.

**Comment by IanMitchell** [comment]
Sure thing! [Working example here](https://github.com/IanMitchell/jekyll_test/commit/7bcb128933d1663f7f978544ff535bea51bf91fa)

If you boot the website up, [the header looks like this](https://gist.github.com/IanMitchell/67d8cd7a7ca4108ae771f2a3f80ed510)

**Comment by benbalter** [comment]
I'm not immediately sure why the footnote is being collapsed into the excerpt, I suspect it's going to be an issue with Jekyll core, as we just call `post.excerpt`, but in the interim you can explicitly set a description to avoid outputting the footnote.

**Comment by IanMitchell** [comment]
Yup, doing that currently. Will poke around jekyll core, thanks!
