### ISSUE TITLE
How to use JSON LD? I don't understand the documentation

### ISSUE THREAD

**Issue by Phlow** [jekyll/jekyll-seo-tag#154]
I can't get the [Customizing JSON-LD output](https://github.com/jekyll/jekyll-seo-tag#customizing-json-ld-output) working. Could you add an example?

In my case, I want to use *links - An array of other URLs that represent the same thing that this page represents. For instance, Jane's bio page might include links to Jane's GitHub and Twitter profiles.*

Is it possible to set these links in *_config.yml* to use them in the layouts? I want to end up like this and I've seen it on Ben Balters website in the source code…

~~~~~
"author": {
		"@type": "Person",
		"name": "{{ site.author }}",
		"sameAs": [
			"https://twitter.com/phlow",
			"https://github.com/phlow",
			"https://www.youtube.com/user/PhlowMedia"
		]
	},
~~~~~

**Comment by DirtyF** [comment]
@Phlow Take a look at [ben's config.yml](https://github.com/benbalter/benbalter.github.com/blob/master/_config.yml#L11-L19) then ;)

**Comment by Phlow** [comment]
I've seen it, and tried to reverse-engineer it but somehow it didn't show up, as I expected. My question: Shouldn't be the documentation be better, than trying to figure it out by stumbling through Bens set-up ;)

**Comment by jhabdas** [comment]
@Phlow I'll try getting it going and grok it. Might be worth a reminder issue in your repo. Think this can be closed now?
