### ISSUE TITLE
Support Author display when posting to Facebook

### ISSUE THREAD

**Issue by jhabdas** [jekyll/jekyll-seo-tag#155]
Currently this plugin does not support Author display when posting to Facebook. Author info can be added in one of two ways (at least):

1. By adding `meta name="author"`; and
1. As well as by adding `meta property="article:author"`.

It's possible to use both, but Facebook prefers use of the later as it allows their parser to dynamically generate a name from a URL (as [shown here with images](https://github.com/jekyll/jekyll-seo-tag/issues/96#issuecomment-275840637)).

I'm opening this up as, even with the resolution of https://github.com/jekyll/jekyll-seo-tag/issues/96#issuecomment-275840637, we still would not have both cases addressed.

**Comment by pathawks** [comment]
Fixed by #103?

**Comment by jhabdas** [comment]
Still need article:author if we want dynamic author links via Facebook share cards (right now they're just static text author names with #103)

**Comment by pathawks** [comment]
And that needs to link to a Facebook profile page?

**Comment by jhabdas** [comment]
> And that needs to link to a Facebook profile page?

Indeed, what's more is it dynamically parses the current page name. So if someone sets the tag and later updates a Page or Person name on Facebook it gets picked up in share, and the name becomes a link to that page.

**Comment by jhabdas** [comment]
Closing this as I see there's `article:publisher` also used for Facebook. Assuming it does the same thing this does. If not, can reopen later.
