### ISSUE TITLE
site.webmaster_verifications not getting printed to page

### ISSUE THREAD

**Issue by davebowker** [jekyll/jekyll-seo-tag#163]
I've entered the config for multiple web service verification as shown in example but it's not being printed out to the page.

I've checked the code within `https://github.com/jekyll/jekyll-seo-tag/blob/master/lib/template.html` and when I manually take that section of code with the liquid if statements and paste it into a random page, it does print out when the site is built, it just doesn't seem to be coming with the {% seo %} tag

**Comment by davebowker** [comment]
Also, looks like Alexa no longer allows you to claim your domain. See here: https://support.alexa.com/hc/en-us/articles/219135887-Claiming-has-been-retired-May-2016

**Comment by rmcfadzean** [comment]
The gem needs a new release to use that.

The latest is 2.1.0 from Nov but that change is from Jan 13.

```ruby
gem 'jekyll-seo-tag', github: 'jekyll/jekyll-seo-tag
```
Works in the mean time if you're ok with pulling from repos.

**Comment by davebowker** [comment]
Ah ok. Yeah pulling directly works
