### ISSUE TITLE
Fix `og:image` to fall back to the site image if one exists

### ISSUE THREAD

**Issue by aarongustafson** [jekyll/jekyll-seo-tag#168]
The `meta` element doesn’t show up at all if `page.image` doesn’t exist.

**Comment by pathawks** [comment]
Duplicate of #97 #95

**Comment by pathawks** [comment]
The reason we want the user to explicitly define an image instead of just falling back to the logo or something is because there may be instances where a user would rather include no image than include the logo. If this is not the case, the user can easily specify a site-wide default image to use.

**Comment by benbalter** [comment]
See https://github.com/jekyll/jekyll-seo-tag#setting-a-default-image

**Comment by mrcoles** [comment]
@benbalter the link has changed, it is now: https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/advanced-usage.md#setting-a-default-image
