### ISSUE TITLE
Poor Man’s Smartypants

### ISSUE THREAD

**Issue by pathawks** [jekyll/jekyll-seo-tag#17]
```text
{% assign seo_title = seo_title | markdownify | strip_html | strip_newlines | escape_once %}
```

What we are doing here is rolling our own SmartyPants implementation in Liquid, which is not great.

Redcarpet has a [fantastic SmartyPants implementation](https://github.com/vmg/redcarpet#also-now-our-pants-are-much-smarter), and is even [already included in GitHub Pages](https://github.com/github/pages-gem/blob/v40/lib/github-pages.rb#L18).

We could implement our own Liquid filter (visible only to this plugin) that will call `Redcarpet::Render::SmartyPants.render`. This way, we could do all of this in one filter instead of four. Additionally, this will properly output the title `#Hashtag` instead of (currently) changing it to `Hashtag` (because Markdown treats the `#` as an `<h1>` tag, which is then stripped).

The only reason I open this as an issue instead of a PR is because requiring Redcarpet gives me pause.

**Comment by benbalter** [comment]
> The only reason I open this as an issue instead of a PR is because requiring Redcarpet gives me pause.

Same here. There's a good chance [GitHub Pages actually drops RedCarpet support in the near future](https://github.com/github/pages-gem/issues/179).

Is there a clean way to create a "macro" for lack of better liquid vocabulary, that would chain those filters and allow us to DRY things up a bit, even if we had to go into Ruby land?

**Comment by benbalter** [comment]
![screen shot 2016-01-06 at 10 48 03 am](https://cloud.githubusercontent.com/assets/282759/12146684/fa60e480-b462-11e5-8fb2-43d0f87bc94a.png)

LOL.

**Comment by pathawks** [comment]
A proper Liquid `smartify` filter has just been added to Jekyll core. jekyll/jekyll#4323

I suppose we should keep the current filter chain for now, but maybe we could move to `smartify` once support has been added to GitHub pages?

**Comment by benbalter** [comment]
> I suppose we should keep the current filter chain for now, but maybe we could move to smartify once support has been added to GitHub pages?

Makes sense. :+1:

**Comment by boturnbow** [comment]
+1

**Comment by pathawks** [comment]
github/pages-gem#289 :tada:

I will work on adding proper Smartypants support when I have some time, if we are ok dropping support for Jekyll 3.0.

**Comment by benbalter** [comment]
>  if we are ok dropping support for Jekyll 3.0.

GitHub Pages should upgrade to Jekyll 3.1 on Monday, and am 👍  dropping pre 3.1 support after that.
