### ISSUE TITLE
Move seo_author_* logic to Ruby

### ISSUE THREAD

**Issue by benbalter** [jekyll/jekyll-seo-tag#176]
The top 100 or so lines of the template is getting a bit unwieldy and I can't imagine it's performant. We should centralize the logic in ruby for figuring out the author (post, data, or global), and any other super-safe hash or string manipulation.

**Comment by pathawks** [comment]
We had talked previously about starting yet another gem to deal with author logic, as anything we do here would also apply to **jekyll-feed** and likely themes as well.

**Comment by benbalter** [comment]
> We had talked previously about starting yet another gem to deal with author logic

Yes! I was thinking step one would be to move it to Ruby here, and then step two could potentially move that to be shared some way once we know it works (e.g., generally make `post.author` a resolved object available to generators).
