### ISSUE TITLE
Liquid Exception: Invalid Date

### ISSUE THREAD

**Issue by aav7fl** [jekyll/jekyll-seo-tag#187]
Using the latest master branch (f048342), I'm getting this error related to `LastModifiedAt`:

```
Liquid Exception: Invalid Date: '#<Jekyll::LastModifiedAt::Determinator:0x000000034cc770 @site_source="/home/kyle/website/aav7fl.github.io", @page_path="/home/kyle/website/aav7fl.github.io/_posts/2013-04-13-somewhere-to-start.md", @opts={}>' is not a valid datetime. in /_layouts/default.html
             ERROR: YOUR SITE COULD NOT BE BUILT:
                    ------------------------------------
                    Invalid Date: '#<Jekyll::LastModifiedAt::Determinator:0x000000034cc770 @site_source="/home/kyle/website/aav7fl.github.io", @page_path="/home/kyle/website/aav7fl.github.io/_posts/2013-04-13-somewhere-to-start.md", @opts={}>' is not a valid datetime.
[17:44:02] 'build' errored after 790 ms
```

Still investigating, but I didn't want a new gem to get pushed out before we figured it out.

Edit 1: It looks to be coming from https://github.com/gjtorikian/jekyll-last-modified-at/blob/master/lib/jekyll-last-modified-at/determinator.rb and how the date is passed into the new template.

`date_modified` in `drop.rb` looks to be the source of the issue.

**Comment by benbalter** [comment]
Suspect we need to call `to_liquid` on `page["last_modified_at"]` in https://github.com/jekyll/jekyll-seo-tag/blob/master/lib/jekyll-seo-tag/drop.rb#L101.

**Comment by aav7fl** [comment]
@benbalter That was it.
