### ISSUE TITLE
JSON-LD errors

### ISSUE THREAD

**Issue by aav7fl** [jekyll/jekyll-seo-tag#190]
In the latest commits (f048342e2296f6a8a915b27eef3326d28e02d7a0), there are a few JSON-LD errors with the Google Structured Data Testing tool when I test against my website. 

1. Author name is missing (Probably because the template is only looking for the `author.name` and not any of the other methods. e.g. `{% assign seo_author = page.author | default: page.authors[0] | default: site.author %}` )
2. Publisher name is missing (same as above)
3. Alt text is now added in the `ImageObject` while the Google Structured Data Testing tool prohibits this. "`The property alt is not recognized by Google for an object of type ImageObject.`'

Screenshot log: http://i.imgur.com/TFvXyn4.png

Let me know if/how you would like to handle those.

**Comment by benbalter** [comment]
Are you able to push up failing tests to reproduce the above? 

For the first, it should be looking to the other means.

**Comment by aav7fl** [comment]
I can try that tomorrow. Will need to freshen up on my Ruby first.

**Comment by aav7fl** [comment]
PR #191 opened with failing test for image tag. 

PR also offers explanation for why the `author` was populated as `null` and why the image object has extra tags.

**Comment by dkmooers** [comment]
I'm having this issue as well. Blog posts are not outputting Author or Publisher at all into JSON-LD, presumably due to OP's suggested reason.

**Comment by aav7fl** [comment]
For me, https://github.com/jekyll/jekyll-seo-tag/pull/192 fixes this (I closed this issue prematurely). Just need to get it pulled into master and the gem updated if it causes no other problems. That should solve your issue, @dkmooers.

**Comment by aav7fl** [comment]
@dkmooers Looks like the PR has been merged and the latest Gem updated with these changes. My issues are solved. Re-open if you're still having an issue.

**Comment by dkmooers** [comment]
Perfect, thanks all!
