### ISSUE TITLE
Run tests locally

### ISSUE THREAD

**Issue by DirtyF** [jekyll/jekyll-seo-tag#195]
Am I the only one not being able to run the tests locally?

```sh
~/code/jekyll/jekyll-plugins/jekyll-seo-tag 
❯ script/cibuild
+ bundle exec rspec
bundler: failed to load command: rspec (/Users/frank/.rbenv/versions/2.3.3/bin/rspec)
Gem::LoadError: You have already activated json 2.1.0, but your Gemfile requires json 1.8.6. Prepending `bundle exec` to your command may solve this.
```

**Comment by benbalter** [comment]
Yes. The issue is the `.ruby-version` file... 2.3.3 and JSON being explicitly required someplace in the stack. I believe HTML Proofer -> Activesupport -> JSON. `bundle update` got things working for me (ActiveSupport >= 4), but with lots of warning. Alternatively, setting Ruby to 2.4.0 locally, resolved the problem as well.

**Comment by DirtyF** [comment]
I switched back to 2.3.3 because this was GitHub Pages current version but it's the same under ruby 2.4

```sh
~/code/jekyll/jekyll-plugins/jekyll-seo-tag master
❯ script/cibuild
+ bundle exec rspec
bundler: failed to load command: rspec (/Users/frank/.rbenv/versions/2.4.1/bin/rspec)
Gem::LoadError: You have already activated json 2.0.3, but your Gemfile requires json 1.8.6. Prepending `bundle exec` to your command may solve this.
```

**Comment by benbalter** [comment]
`gem uninstall json`? or `gem install json`? Some combination of the above now has it work on 2.3.3 with no warnings.

**Comment by DirtyF** [comment]
Finally got it working with:

```sh
bundle clean --force
gem cleanup
script/bootstrap
```

💎  🔧  🌞  … thanks for your feedback @benbalter
