### ISSUE TITLE
Having a list of authors on a single post causes build to break

### ISSUE THREAD

**Issue by RohitK89** [jekyll/jekyll-seo-tag#208]
Related to: https://github.com/jekyll/jekyll-seo-tag/issues/196

I've modified my code to allow more than one person as an author on a blog post.
```
---
...
authors:
  - foo
  - bar
---
```

This causes the build to break with this plugin enabled.

Error:
```
Liquid Exception: no implicit conversion of String into Integer in /_layouts/default.html
jekyll 3.4.3 | Error:  no implicit conversion of String into Integer
```

Thanks for looking into it!

**Comment by benbalter** [comment]
@RohitK89 is this with version 2.2.3?

**Comment by RohitK89** [comment]
@benbalter 2.2.2, apparently. It's what Github Pages seems to be using

**Comment by benbalter** [comment]
I believe this should be fixed in v2.2.3 (which specifically addressed this issue).

**Comment by RohitK89** [comment]
Ah. Thanks! Good to know. Any idea how often GitHub Pages updates the gems?

**Comment by RohitK89** [comment]
@benbalter Seems to still be broken with 2.2.3.

```
bundle show
* jekyll-seo-tag (2.2.3)
```
```
rkapur@rkapur-MBP flatironhealth.github.io (rkapur/qs_onboarding_post)*$ bundle exec jekyll serve
 Incremental build: disabled. Enable with --incremental
      Generating...
  Liquid Exception: no implicit conversion of String into Integer in /_layouts/default.html
jekyll 3.4.3 | Error:  no implicit conversion of String into Integer
```

**Comment by RohitK89** [comment]
Never mind. I see that 2.2.3 fixes it if you supply an authors list with the tag `authors` plural instead of `author` singular.
