### ISSUE TITLE
Mistake in the README.me file (Installation Section)

### ISSUE THREAD

**Issue by mittalyashu** [jekyll/jekyll-seo-tag#216]
In the README.md file.

In the Installation section:
1.  Install the Jekll seo tag gem using `Command Prompt`:
```
gem install jekyll-seo-tag
```

2.  Add the following to your site's `Gemfile`:
```
gem jekyll-seo-tag
```

3.  Add the following to your site's `_config.yml`:
```
gems:
  - jekyll-seo-tag
```
4.  Add the following right before `</head>` in your site's template(s):
```
{% seo %}
```

**Comment by pathawks** [comment]
What is the mistake?

**Comment by mittalyashu** [comment]
![image](https://user-images.githubusercontent.com/29014463/27261643-e6d26fe4-5464-11e7-9df1-a84e16936065.png)

Check this image. It is the screenshot of the README.me file of the installation section.

**Comment by DirtyF** [comment]
@mittalyashu When you use a Gemfile, you're supposed to run `bundle install` to install. Feel free to open a PR if you think this step is missing for users not familiar with `bundler`.

**Comment by ashmaroli** [comment]
@mittalyashu There is no mistake here.

There are two types of plugins: **Gem-based plugins** and **Local plugins**

Gem-based plugins are packages usually consisting of numerous `.rb` files, but may contain a single `.rb` file as well, and are generally hosted at `https://rubygems.org/gems/`. They're run by Jekyll based on your config file and `Gemfile`.

Local plugins are understandably a single `.rb` that contains all the code and are hosted within your site and run from inside the `_plugins` directory.

---
`JekyllSeoTag` is a gem-based plugin and there is no need to have it added to the `_plugins` folder for it to work. It just needs to be added as documented. When you run `bundle exec jekyll serve`, the plugin will be run by Jekyll

**Comment by mittalyashu** [comment]
@ashmaroli It's it will be better, if it is mentioned in the README.md file itself.

`There are two types of plugins: Gem-based plugins and Local plugins`

**Comment by ashmaroli** [comment]
> it will be better, if it is mentioned in the README.md file itself.

Its not an official distinction, but simply terms I invented to help make the concept clear to you.
Besides, this info should be added to the docs for Jekyll itself instead of a documentation for a  Jekyll Plugin such as `SeoTag`
