### ISSUE TITLE
Allow turning off Twitter Summary Card

### ISSUE THREAD

**Issue by logankp** [jekyll/jekyll-seo-tag#217]
I utilize the Author object in _config.yml for the theme I'm using (Minimal Mistakes). I'd like the ability to use the seo plugin without having a Twitter Summary Card generated as I have no Twitter account.

Is there currently a way to turn this feature off?

**Comment by DirtyF** [comment]
> I'd like the ability to use the seo plugin without having a Twitter Summary Card generated as I have no Twitter account.

Twitter Cards are useful even if you don't have a Twitter account, and every tweet linking to a post on your blog will embed the associated image and description.

**Comment by logankp** [comment]
True, but I'd rather just not have any Twitter integration while still enjoying the rest of the benefits of this plugin.

**Comment by DirtyF** [comment]
If you don't set `twitter.username` in your config_yml, no twitter markup is being generated.

**Comment by logankp** [comment]
That did it! Just had to completely delete the twitter lines in _config.yml instead of just setting them to blank.
