### ISSUE TITLE
<title>-tag on pages gets wrong page.name on githubpages.io

### ISSUE THREAD

**Issue by mehmandarov** [jekyll/jekyll-seo-tag#220]
When deployed to gihubpages, <title>-tag gets wrong value from SEO-plugin. The title gets set to for example "Home | user.github.io" instead of "Home | {{site.name}}". This works totally fine locally, thoguh. Example: https://mehmandarov.com/

**Comment by benbalter** [comment]
Per [the usage instructions](https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md#usage) you should be using `site.title`, not `site.name`.

**Comment by wsdjeg** [comment]
@benbalter if I want the title `Home - SiteName` instead of `Home | SiteName`, how could I do?

**Comment by DirtyF** [comment]
@wsdjeg You can't choose the TITLE_SEPARATOR at the moment.

**Comment by wsdjeg** [comment]
@DirtyF Thanks for your info, and Thanks for this plugin. :heart:
