### ISSUE TITLE
Prefer site.name over site.title

### ISSUE THREAD

**Issue by benbalter** [jekyll/jekyll-seo-tag#238]
We currently will use both `site.name` or `site.title` so that users previously using `site.name` (a common design pattern) don't have to change their site to use the plugin:

https://github.com/jekyll/jekyll-seo-tag/blob/7313ee7e503b3ac2064e8930ee63895f7a94769e/lib/jekyll-seo-tag/drop.rb#L30-L32

We prefered `site.title` and recommend it in our documentation, because it mirrors `post.title` (so as not to introduce an additional field), meaning if both are set, we'll use `site.title`.

This has a strange interaction with Jekyll GitHub Metadata, in that we set `site.title` to the repository name, if none is set, by default, meaning, on GitHub Pages, `site.name` is never used, leading to some confusing circumstances:

https://github.com/jekyll/github-metadata/blob/3765032e8a3067eb8b57129496cf78312dda9cc9/lib/jekyll-github-metadata/site_github_munger.rb#L56-L59

So a few potential options:

1. SEO Tag should prefer `site.name` over `site.title`. This would be strange, in that our docs would recommend `site.title`, but if a user accidentally also had `site.name` set, we'd ignore their preference (and our suggestion).

2. GitHub Metadata should not set anything if `site.title` OR `site.name` is set. This could lead to some strangeness again, where a user sets `site.name` but relies on `site.title` to be set by GitHub.

3. GitHub Metadata should copy `site.name` to `site.title` if it's set. This would allow consistency so that `site.title` is always set as the user's intended title (while still being backwards compatible with `site.name`). This feels like magic to me and not related to either plugin's purpose.

4. GitHub metadata should set both `site.name` and `site.title` if either is not set. This could lead to further inconsistency.

5. GitHub metadata should set both `site.name` and `site.title` to the same value, preferring `site.title`, then `site.name`, then the repo name. This would at least create consistency in some more situations. 

Thoughts? I'm leaning towards 2 as the best solution, as it's the least magic and most predictable if properly documented. If a user explicitly sets `site.name` we shouldn't jump in and also set `site.title`.

/cc @parkr who always has good thinking around these types of problems (or at least agrees with me :smile:)

**Comment by parkr** [comment]
6: Deprecate `site.name` in favor of `site.name`. The site doesn't have a name, it has a title, and consistency is our guiding light.

😏

**Comment by benbalter** [comment]
@parkr Makes sense. Would you expect Jekyll SEO tag and/or Jekyll Metadata to give you a warning in any of the above cases?

**Comment by parkr** [comment]
> Would you expect Jekyll SEO tag and/or Jekyll Metadata to give you a warning in any of the above cases?

If we deprecated `site.name` in favor of `site.title`, it'd definitely be nice to have a warning. We'll definitely have to fall back to `site.name` indefinitely, but adding a warning would be neat.

> Makes sense

LOL I had a typo that made it completely confusing.

Option 2 is also a perfectly fine solution under the principle of least surprise. I trust your judgement here. 👍

**Comment by benbalter** [comment]
👍 I think the best option sounds like option 8 (2+6). I'll update GitHub metadata to throw a warning and do nothing if `name` is set (formally deprecating `name` if favor of `title`).
