### ISSUE TITLE
JSON-LD publisher output

### ISSUE THREAD

**Issue by innopal** [jekyll/jekyll-seo-tag#240]
First off, thank you for a super useful plugin.

I can't figure out a way around an issue though.
I am getting an error from google's Stuct data testing tool:(
publisher is null for my BlogPosting schema type, and google's struct validation tool says it is required.
Is this a bug? No matter where I set the publisher it is always null.
I looked at the source code and it seems like it is setting the publisher from "logo", so I set a logo parameter in my document's frontmatter but no luck there either.

Any ideas?

**Comment by DirtyF** [comment]
Could you provide a link to the validation error message?

**Comment by innopal** [comment]
No problem! Here it is:
[](https://search.google.com/structured-data/testing-tool/u/0/#url=http%3A%2F%2Fblog.tournamatic.com%2Fschedule-your-tournament)

**Comment by innopal** [comment]
https://search.google.com/structured-data/testing-tool/u/0/#url=http%3A%2F%2Fblog.tournamatic.com%2Fschedule-your-tournament

**Comment by antoniotrento** [comment]
Same problem here guys : [Structured data validator don't find publisher](https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Flantoniotrento.github.io%2Fweb-marketing%2F2017%2F11%2F06%2Fi-miogliori-strumenti-per-far-crescere-i-social-network)

**Comment by ananthp** [comment]
`publisher` field is null for all my pages too.

**Comment by benbalter** [comment]
Here's the relevant logic:

https://github.com/jekyll/jekyll-seo-tag/blob/38b0fbd73ae3205b0673f5649311ed47cc7a1b5d/lib/jekyll-seo-tag/json_ld_drop.rb#L53-L64

If logo is not set, it will be `nil` in all cases (Because logo is a require property, IIRC). Is it possible that that is the case here?

**Comment by antoniotrento** [comment]
Seem solve my problem! @benbalter Thanks a lot for your time! I really appreciate your help.

I hope that also for other users who have the same problem has been useful.

A great day. Antonio

**Comment by benbalter** [comment]
@antoniotrento please feel free to submit a pull request to update the documentation to clarify this behavior, if you'd like.

**Comment by antoniotrento** [comment]
Done [in this pull request](https://github.com/jekyll/jekyll-seo-tag/pull/253)

**Comment by robertosimoes** [comment]
First of all, I'd like to thank you for sharing this great work!
I'm new to Jekyll, and this plugin is saving my life.

It looks like this pull request solves Google's structured data validation for the publisher. But it doesn't allow to have a different publisher and author. Having different publisher and authors is useful for blogs that have multiple authors, but everybody is under the same Organization.
