### ISSUE TITLE
image support for github resources

### ISSUE THREAD

**Issue by wsdjeg** [jekyll/jekyll-seo-tag#258]
I hope the `image` option support value like:

https://cloud.githubusercontent.com/assets/13142418/26402270/28ad72b8-40bc-11e7-945e-003f41e057be.png

which is uploaded from the comment box.

**Comment by benbalter** [comment]
Thanks for this. It should work. Do you mind providing a bit more information about what problem you're trying to solve? What have you tried that didn't work?

**Comment by wsdjeg** [comment]
@benbalter Thanks, I want to know if I use a image like this , the url is not same as my website, will te break the seo?

**Comment by benbalter** [comment]
It should not affect your SEO, and the plugin should support you linking to an external resource.

**Comment by wsdjeg** [comment]
OK， Thanks. I am closing the issue.
