### ISSUE TITLE
Define image base path? 

### ISSUE THREAD

**Issue by alvarotrigo** [jekyll/jekyll-seo-tag#262]
In the front matter of every post I'm using a `image` variable like this:
```shell
image:  myimage.png
```
I use it for my own purposes in the list of posts and in the post itself.

Right now, the seo-tag plugin creates the following:
```html
<meta property="og:image" content="https://example.com/blog/myimage.png" />
```

But I need the path to be within the `assets/imgs/` folder:

```html
<meta property="og:image" content="https://example.com/blog/assets/imgs/myimage.png" />
```

Is there a way to add a base path to the image path? 
I would very much prefer not having to define it in every post front matter.

**Comment by pathawks** [comment]
> Is there a way to add a base path to the image path?

This is not currently possible, no.

**Comment by alvarotrigo** [comment]
So.... we have to specify the full path on every single post? 
Is that how it is mean to work then?

**Comment by pathawks** [comment]
That is correct.

Jekyll assumes nothing about how your assets are organized. If it is an absolute URL, it will be used as is. If it is a relative URL, it will be appended to the site’s root URL.

**Comment by alvarotrigo** [comment]
Any way to run this plugin locally? So I can modify the plugin within my project?
I've tried moving the content of `lib` to my `_plugins` folder, then removing it from the global path in my computer. 

![screen shot 2018-01-07 at 18 20 23](https://user-images.githubusercontent.com/1706326/34651906-77f7bb5c-f3d7-11e7-84fb-495a045605cd.png)

Now I'm getting the following error:

> [18:18:33] Jekyll: jekyll 3.6.2 | Error:  uninitialized constant Jekyll::SeoTag::UrlHelper

```
plugins:
    - jekyll-feed
    - jekyll-paginate-v2
    - jekyll-sitemap
    - jekyll-seo-tag
    - include-absolute
    - lazy-images
```

**Comment by pathawks** [comment]
I don't know if it's possible to copy the plugin into the `_plugins` directory; this is not a supported use case for this plugin. I believe any plugin in the `_plugins` directory needs to be contained in a single file.

**Comment by alvarotrigo** [comment]
> I believe any plugin in the _plugins directory needs to be contained in a single file.

Ok, thanks for the info! ;)

**Comment by totomobile43** [comment]
Essentially ~0% of sites keep their image at the root URL, so why have this as a default in the first place?

**Comment by alvarotrigo** [comment]
@TerminalAddict nah, they never really inteded to solve this issue. 
I had to add the whole path in every single post, for example:

    image: /assets/imgs/image.png

**Comment by regpaq** [comment]
I'm having this same challenge. I'd like to customize the output of this plugin a bit more. I can edit the template.html file and get what I want locally and to github, but when deployed to netlify, it doesn't take my modifications and I don't understand why
