### ISSUE TITLE
Display crowdsourced best-practices in README.md

### ISSUE THREAD

**Issue by inwardmovement** [jekyll/jekyll-seo-tag#266]
Wouldn't it be great to detail what "battle-tested crowdsourced best-practices" the plugin is based on?

**Comment by benbalter** [comment]
That is a reference to the specific implementations of the features listed in https://github.com/jekyll/jekyll-seo-tag#what-it-does. The details are frequently tweaked based on real-world use, and I don't think it would be practical to enumerate each specific implementation.
