### ISSUE TITLE
Install docs: `{% seo %}`is being substituted 

### ISSUE THREAD

**Issue by Kraymer** [jekyll/jekyll-seo-tag#267]
At https://jekyll.github.io/jekyll-seo-tag/installation/ we have : 

> Add the following right before </head> in your site’s template(s):
>
>   
> <title>Installing Jekyll SEO Tag | Jekyll SEO Tag</title>
> <meta property="og:title" content="Installing Jekyll SEO Tag" />
> <meta property="og:locale" content="en_US" />
> <meta name="description" content="A Jekyll plugin to add metadata tags for search engines and social networks to better index and display your site’s content." />
> <meta property="og:description" content="A Jekyll plugin to add metadata tags for search engines and social networks to better index and display your site’s content." />
> <link rel="canonical" href="http://jekyll.github.io/jekyll-seo-tag/installation/" />
> <meta property="og:url" content="http://jekyll.github.io/jekyll-seo-tag/installation/" />
> <meta property="og:site_name" content="Jekyll SEO Tag" />
> <script type="application/ld+json">
> {"name":null,"description":"A Jekyll plugin to add metadata tags for search engines and social networks to better index and display your site’s content.","author":null,"@type":"WebPage","url":"http://jekyll.github.io/jekyll-seo-tag/installation/","image":null,"publisher":null,"headline":"Installing Jekyll SEO Tag","dateModified":null,"datePublished":null,"sameAs":null,"mainEntityOfPage":null,"@context":"http://schema.org"}</script>
> 

whereas it should be :  

> Add the following right before </head> in your site's template(s):
> {% seo %}

Problematic because I arrived tat htps://jekyll.github.io/jekyll-seo-tag/installation via a google search and genuinely believed it was the "official" install page for the plugin

**Comment by DirtyF** [comment]
@Kraymer good catch, looks like the tag is being interpreted by GitHub Pages here.

**Comment by DirtyF** [comment]
@Kraymer Thanks for reporting, this is fixed now 🌮 🍺

**Comment by Kraymer** [comment]
:+1:
