### ISSUE TITLE
Installation Documentation is Misleading.

### ISSUE THREAD

**Issue by cdr255** [jekyll/jekyll-seo-tag#275]
In the installation documentation, it currently reads as though You are supposed to put the following before `</head>`:

    {% raw %}
    {% seo %}
    {% endraw %}

Since the correct way is simply including:

    {% seo %}

Shouldn't it be listed as such?

**Comment by ashmaroli** [comment]
The `{% raw %}` `{% endraw %}` is there to simply prevent Jekyll from processing the `{% seo %}` when the Markdown document is processed into the [HTML page](https://jekyll.github.io/jekyll-seo-tag/installation/)

We tried to reduce confusion by placing the `raw` tags outside the fenced-code-block in the Markdown document

**Comment by DirtyF** [comment]
I thought adding comments would prevents GitHub from showing the `raw` tags when browsing the markdown files.

Change was introduced in https://github.com/jekyll/jekyll-seo-tag/pull/273/files

We need the `raw` tag for the documentation website:
https://jekyll.github.io/jekyll-seo-tag/installation/

**Comment by cdr255** [comment]
@DirtyF That was exactly what I was going to suggest. 

The issue is that comments were not also used for the `installation.md` file: https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/installation.md

Currently, the `{% raw %}` tags are uncommented, and are thus visible if a user clicks on the Installation documentation link in the README.md: https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/README.md
