### ISSUE TITLE
<title>-Tag is completely messed up

### ISSUE THREAD

**Issue by mosesontheweb** [jekyll/jekyll-seo-tag#278]
Hi,

another issue I recognized is that SEO tag somehow messes up the <title>-tag. I expected that it would use only the title specified in _config.yaml, but in fact it uses title + | (dash) + description.

Is this normal?

Regards, Thomas

**Comment by benbalter** [comment]
This is the intended behavior as an SEO best practice. See [the "What it does" section of the README](https://github.com/jekyll/jekyll-seo-tag#what-it-does):

> Page title, with site title or description appended

**Comment by tabasko78** [comment]
Hi, I have the same problem :(
This can't be the best SEO practice.
SEO is my main job for this last 13 years this is the very first time I read that :)

Anyway, main goal is to know if I can correct the scheme ?
Thanks for your help.
