### ISSUE TITLE
og:image is not outputed

### ISSUE THREAD

**Issue by emirkin** [jekyll/jekyll-seo-tag#279]
Strangely, no setting of `image` or `logo` in `_config.yml` sets `og:image` in the *home* page. Yes, I did restart `jekyll serve`.

**Comment by ashmaroli** [comment]
SEOTag is rendered per page in your site.
Try setting the `image` in your post's front matter..

**Comment by emirkin** [comment]
Right. It is the **home** page that does not get it. I do have `image: ` there as well.
