### ISSUE TITLE
Altering home page with front matter

### ISSUE THREAD

**Issue by influentialcode** [jekyll/jekyll-seo-tag#282]
I'm attempting to alter the seo output for the home page using front matter on `_layouts/home.html` but the values that I'm setting don't seem to be having an effect on the output. For instance, I've tried to set the title and description but they're ignored. I've successfully changed the output for other pages such as Contact (`/contact.md`) using front matter so I'm confident that it's not a cache problem. 

I'll caveat the following by saying that I'm not a Ruby developer: I attempted to look through the code for something that prevents home page alteration but nothing was obvious to me. I didn't see anything in the usage or advanced usage section that indicates this isn't possible. Is there something that I'm doing incorrectly or misunderstanding? Thanks.

**Comment by DirtyF** [comment]
Have you tried with `index.html` or `index.md` instead of the layout file?

**Comment by influentialcode** [comment]
Thank you for the quick response. I added an attribute to the `index.md` and saw the change in the output. Thanks for the suggestion. 

For my own understanding, I have a couple questions if you don’t mind. I hadn’t added any attributes to that file because there’s a note in it to make changes to the layout file. Is it common or the intended use case to add front matter to `index.md`? Also, is there some type of order of operations that front matter is applied given that adding something to the template didn’t have an effect but the markdown file did?

Thanks again.

**Comment by DirtyF** [comment]
> I hadn’t added any attributes to that file because there’s a note in it to make changes to the layout file.

Sorry for the confusion, but yeah you should add the Front Matter for the SEO in the targeted page, *not* the layout. 

What we mean here is if that you wanna change the layout of the index page, you should modify `_layout/home.html`. If you can think of a better way of conveying this info, we'll be happy to make that change.

See how the plugin fetch the Front Matter of the **page** and default to **site** if missing:

https://github.com/jekyll/jekyll-seo-tag/blob/3414b176607e304d756932deb4365a2562364084/lib/jekyll-seo-tag/drop.rb#L41-L43

https://github.com/jekyll/jekyll-seo-tag/blob/master/lib/jekyll-seo-tag/drop.rb#L77-L81
