### ISSUE TITLE
Customize twitter:card value?

### ISSUE THREAD

**Issue by ng-chicago** [jekyll/jekyll-seo-tag#287]
Would be good if you could pick the twitter:card value
Looks like it always defaults to **_summary_large_image_** only if there is an image?
Usually using **_summary_** in looks much better (IMHO)

This places a large stretched image across the whole card
        meta name="twitter:card" content="summary_large_image"
        meta name="twitter:image" content="http://mySite.com/assets/myImage.png"

This places image as square to left of card
        meta name="twitter:card" content="summary"
        meta name="twitter:image" content="http://mySite.com/assets/myImage.png"

Image with **_summary_** value
![screen shot 2018-05-09 at 11 55 16 am](https://user-images.githubusercontent.com/25120169/39828266-f9530fd2-537f-11e8-8b50-114db73cf607.png)

**Comment by ng-chicago** [comment]
@XhmikosR  I THINK they are working on it, but it is not yet in the current version I downloaded
See this commit here
https://github.com/jekyll/jekyll-seo-tag/commit/643c2dbb06e99e876b4e1a62c922f117b64e1c14

**Comment by XhmikosR** [comment]
Ah, that would explain it because the instructions refer to the master version.

@parkr @pathawks @benbalter: can you release a new version?

**Comment by pathawks** [comment]
You're right; it looks like it's time for a new release. See also #270
