### ISSUE TITLE
use https instead of http for schema.org link

### ISSUE THREAD

**Issue by mkoohafkan** [jekyll/jekyll-seo-tag#294]
I recently switched to https for my Github-pages site, and I'm seeing a mixed-content warning on (some) browsers. I checked the page source and the only plain http reference I see is to http://schema.org, which I think is generated by the jekyll-seo-tag gem. Any chance you can update the gem to use https://schema.org instead?

**Comment by pathawks** [comment]
Good idea. This is [fully supported by schema.org](https://schema.org/docs/faq.html#19) and, like you say, might be good for us to adopt.

Care to open a pull request?

**Comment by DirtyF** [comment]
Fixed in #296
