### ISSUE TITLE
Feature Request: Allow removing generator meta tag

### ISSUE THREAD

**Issue by philippemarlin** [jekyll/jekyll-seo-tag#307]
Hi,
Is it possible with option to remove this line ?
 `<meta name="generator" content="Jekyll v3.3.1" />`

**Comment by ashmaroli** [comment]
Why do you want to remove it??

**Comment by philippemarlin** [comment]
it's a footprint in Se0

**Comment by ashmaroli** [comment]
More details, please.
How is this "footprint" hampering your site's SEO?

**Comment by philippemarlin** [comment]
it's a footprint will can trace a website technology for private bl0g

**Comment by philippemarlin** [comment]
@DirtyF i know that is a minority (source you can use https://www.wappalyzer.com/ ). But if all websites who push to your money site with same footprint is a danger. I do wp jekyll homemade and more but if the footprint are more removed is great.

**Comment by ashmaroli** [comment]
Closing as this has been marked as "wont-fix". Will reopen if a better use case can be demonstrated.
