### ISSUE TITLE
Override `template.html`

### ISSUE THREAD

**Issue by infojunkie** [jekyll/jekyll-seo-tag#308]
I'd like to override the default `template.html` - in my case, I'd like to always show a Twitter `summary` card.  Is there a recommended way to do so?

**Comment by pathawks** [comment]
If you want to override the template, you probably don’t want to be using this plugin in the first place.

**Comment by infojunkie** [comment]
lol thanks

**Comment by infojunkie** [comment]
In case anyone else is wondering too, here's a simple way to override the template: https://github.com/meedan/meedan.code/commit/a9ad6e794fffd35035aa7e5bfb1200a34fe0e479
