### ISSUE TITLE
link rel next/prev are missing the trailing slash

### ISSUE THREAD

**Issue by XhmikosR** [jekyll/jekyll-seo-tag#322]
Example:

```
<link rel="prev" href="https://blog.getbootstrap.com/page2" />
<link rel="next" href="https://blog.getbootstrap.com/page4" />
```

Branch https://github.com/twbs/bootstrap-blog/tree/xmr-seo-tag

**Comment by ashmaroli** [comment]
@XhmikosR This looks like an issue with `jekyll-paginate` since `jekyll-seo-tag` does not alter the
`{{ paginator }}` object.

**Comment by XhmikosR** [comment]
OK I saw https://github.com/sverrirs/jekyll-paginate-v2 but it's not officially allows on GitHub Pages. I wish they moved faster.

**Comment by ashmaroli** [comment]
There are talks of adopting https://github.com/sverrirs/jekyll-paginate-v2 as the spiritual successor but there are no official plans underway..

**Comment by XhmikosR** [comment]
GutHub needs to step up its game. It's so annoying we can't use autoprefixer and so many other mandatory plugins. Oh, well, sorry for ranting.

**Comment by ashmaroli** [comment]
You could just deploy your blog via other players (like https://www.netlify.com)..

**Comment by XhmikosR** [comment]
I could but you see the irony here, though. Mark works for GitHub :P

**Comment by DirtyF** [comment]
@XhmikosR As long as source code is hosted on GitHub, I don't see why hosting an open-source project on Netlify would be a problem. [GitHub Actions](https://github.com/actions) shows that GitHub can interact with orher services, as long as it remains the single source of truth.

**Comment by XhmikosR** [comment]
Or they could try and be more active too. The problem isn't how the end user can work around such issues. The problem is GitHub not doing much (at least publicly) to improve their product.

But anyway.

**Comment by DirtyF** [comment]
As far as I know it's not in GitHub's plans to work on improving GitHub Pages, they focus on their main product, hosting source code, the one that is profitable, which is perfectly understandable.
