### ISSUE TITLE
Wrong text in `usage` docs.

### ISSUE THREAD

**Issue by ali-hardan** [jekyll/jekyll-seo-tag#327]
At [here](https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md), You said  `date_modified is subset of social`. It's wrong and it not works when we use it under `social`, It works under `seo`.

**Comment by ashmaroli** [comment]
@ali-hardan Are you willing to submit a PR to fix it..?

**Comment by ali-hardan** [comment]
@ashmaroli No, because my English is not such good.
