### ISSUE TITLE
Prevent converting %2F to / in images

### ISSUE THREAD

**Issue by mikkopaderes** [jekyll/jekyll-seo-tag#349]
So my images contains `%2F` in their name that I don't want to convert to `/`.

Here's an example: https://firebasestorage.googleapis.com/v0/b/cenchat-app.appspot.com/o/assets%2Fimages%2Flogos%2Fcenchat-icon-wob-192.png?alt=media&token=7290d055-156c-467a-a4fb-69dda5842b71

If we convert that to:

https://firebasestorage.googleapis.com/v0/b/cenchat-app.appspot.com/o/assets/images/logos/cenchat-icon-wob-192.png?alt=media&token=7290d055-156c-467a-a4fb-69dda5842b71

It becomes inaccessible. Is there anyway to configure not encoding the URL for images?

**Comment by ashmaroli** [comment]
@mikkopaderes Have you found a solution for this?

**Comment by mikkopaderes** [comment]
@ashmaroli no I didn't but I figured that the easiest fix would just to not host these assets in Google Cloud Storage.
