### ISSUE TITLE
site's description looks weird after adding jekyll-seo-tag

### ISSUE THREAD

**Issue by khvnhtung** [jekyll/jekyll-seo-tag#353]
<img width="622" alt="Screen Shot 2019-07-02 at 10 55 47 PM" src="https://user-images.githubusercontent.com/33808069/60527522-9969be80-9d1c-11e9-994a-90df444f1993.png">
As you can see here. It looks like it was scrambled. I tried wrapping  a < head > tag around the `{ seo }` and re reading the documentation to make sure I was following all the steps. Can someone have a look at this? Thanks!

**Comment by ashmaroli** [comment]
What does the *unscrambled* description look like?

**Comment by khvnhtung** [comment]
Well, what I included in the config.yml description was "blog about all kinds of stuff" so I guess it should have been the site's description right?

**Comment by ashmaroli** [comment]
@khvnhtung We need more context to help you resolve this issue.
What version of the plugin and Jekyll are you using?
Are you using a theme..?

If nothing, is the site's source public?

**Comment by khvnhtung** [comment]
@ashmaroli 
Okay. I'm currently using the [Contrast theme](https://github.com/niklasbuschmann/contrast)
Jekyll version: 3.8.6 (checked using Jekyll -v)
Plugin (Jekyll Seo Tag) version: 2.6.1 (checked using gem list)
Ah and you can check out the site's source [here](https://github.com/khvnhtung/khvnhtung.github.io)

**Comment by ashmaroli** [comment]
@khvnhtung I don't see any scrambling in your hosted site nor could I reproduce your issue by cloning the repo locally.
Hence closing it.
