### ISSUE TITLE
Why is there no og:image and twitter:image tags?

### ISSUE THREAD

**Issue by kvanlombeek** [jekyll/jekyll-seo-tag#384]
These image tags are important to display the website attractively when somebody shares the site on Twitter or Facebook or Whatsapp.

**Comment by ashmaroli** [comment]
The plugin does render these tags:
https://github.com/jekyll/jekyll-seo-tag/blob/38ef0bea229de85f25b5735c432587c09b494398/lib/template.html#L32-L40
https://github.com/jekyll/jekyll-seo-tag/blob/38ef0bea229de85f25b5735c432587c09b494398/lib/template.html#L55-L60

Perhaps you'd like to take a look at the documentation:
https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
