### ISSUE TITLE
How to I get the SEO title as Just post tile

### ISSUE THREAD

**Issue by BhuviTheDataGuy** [jekyll/jekyll-seo-tag#387]
Right now the default SEO title will be taken like `Post title |  title `

But I want to make the post title only as my SEO title I don't want the pipe and then the title of my blog.

### EG:

Blog title: Jekyll Guides

### Current: 
`how to start with Jekyll | Jekyll Guides`

### Expected
`how to start with Jekyll`

**Comment by LorenzBung** [comment]
One option:

In your `<head>` of the layout template for your posts, replace `{% seo %}` with:
```liquid
{% seo title=false %}
<title>{{ page.title }}</title>
```

**Comment by BhuviTheDataGuy** [comment]
But will it disable other meta properties like Description.?

**Comment by LorenzBung** [comment]
[I don't think so](https://github.com/jekyll/jekyll-seo-tag/blob/6135021410981d2d76878568e9c21cf363882bfe/lib/template.html#L3).
