### ISSUE TITLE
Jekyll 4.1.0 breaks Travis tests

### ISSUE THREAD

**Issue by emmasax4** [jekyll/jekyll-seo-tag#394]
Using Jekyll version 4.1.0 (which was released the other day) breaks Travis tests. The `.travis.yml` file should lockdown Jekyll to `~> 4.0.0` or fix the tests: https://github.com/jekyll/jekyll-seo-tag/blob/master/.travis.yml#L18.

Long story short, I was fiddling around with a fork, and found that the later version breaks: https://travis-ci.com/github/emma-sax4/jekyll-seo-tag/builds/168817663. But locking down Travis succeeds again: https://travis-ci.com/github/emma-sax4/jekyll-seo-tag/builds/168820682.

**Comment by ashmaroli** [comment]
@emmasax4 Jekyll 4.1.1 has been shipped. Can you verify if this is still an issue?
Thanks.

**Comment by emmasax4** [comment]
Yep, the issue is resolved now. I'll make [a pull request](https://github.com/jekyll/jekyll-seo-tag/pull/405) to lock down the version of Jekyll that Travis uses.
