### ISSUE TITLE
How to use seo_paginator_message

### ISSUE THREAD

**Issue by LorenzBung** [jekyll/jekyll-seo-tag#400]
Hi,

I've tried to set [site.seo_paginator_message](https://github.com/jekyll/jekyll-seo-tag/blob/6135021410981d2d76878568e9c21cf363882bfe/lib/jekyll-seo-tag/drop.rb#L200) to something like `"Current: %<current>s, total: %<total>s, title: "` (just to try), but I still get
```html
<title>Page 4 of 5 for ...</title>
```
Can somebody help with this?

**Comment by ashmaroli** [comment]
This feature has not been released yet. So you won't have it on GitHub Pages.
Elsewhere, you can point your Gemfile to this repository:
```ruby
gem "jekyll-seo-tag", github: 'jekyll/jekyll-seo-tag'
```

**Comment by LorenzBung** [comment]
Ahh, thanks for your help! I'll write the title manually then.
