### ISSUE TITLE
Site description in config doesn't work with Jekyll 4.1.0

### ISSUE THREAD

**Issue by canicodenow** [jekyll/jekyll-seo-tag#401]
With 4.0.0, setting a description field in config.yml added this content to the description for SEO-tag for pages where a front matter description wasn't set.

With 4.1.0, unless description is set for the page's front matter, it picks up all the page content as the description.

**Comment by ashmaroli** [comment]
@canicodenow The reason for this is because Jekyll 4.1.0 introduced *page excerpts by default*.
Jekyll repo's `master` branch has patched the issue. You may point to the repository, if you want:
```ruby
gem 'jekyll', github: 'jekyll/jekyll'
```

**Comment by ashmaroli** [comment]
@canicodenow Jekyll 4.1.1 has been shipped. Can you verify if this is still an issue?
Thanks.

**Comment by websupportESCC** [comment]
> @canicodenow Jekyll 4.1.1 has been shipped. Can you verify if this is still an issue?
> Thanks.

I've just updated and it's picking up the description as normal now. So this is fixed - thanks @ashmaroli

**Comment by canicodenow** [comment]
> @canicodenow Jekyll 4.1.1 has been shipped. Can you verify if this is still an issue?
> Thanks.

I've just updated and it's picking up the description as normal now. So this is fixed - thanks @ashmaroli
