### ISSUE TITLE
Setting for HTML5-compliant meta tags

### ISSUE THREAD

**Issue by martinbean** [jekyll/jekyll-seo-tag#412]
I’ve noticed that this plugin generates XML-style self-closing tags (i.e. `<meta name="" content="" />`) but in HTML5, `meta` elements are _void_ elements, and therefore don’t have an end tag (spec: https://www.w3.org/TR/2011/WD-html-markup-20110113/syntax.html#void-element).

Is it possible to get a configuration option that generates valid HTML5 meta tags, i.e. `<meta name="" content="">`?

**Comment by DirtyF** [comment]
This is also valid in HTML5. Jekyll website use this plugin, and no error output in the W3C validator related to this meta.

https://validator.w3.org/nu/?doc=https%3A%2F%2Fjekyllrb.com%2F
