### ISSUE TITLE
Couldn't locate where to add in {% seo %}

### ISSUE THREAD

**Issue by LilianYou** [jekyll/jekyll-seo-tag#416]
Dear experts,

Please excuse me if this question sounds naive. I am new to webpage development and I am following the instructions on this repo [jekyll-seo-tag](https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/installation.md) to add in the SEO tag. However, for step 3, I can not locate a file in my folder where I could add in {% seo %}. I attached a screenshot of all the files in my web folder below, could you please point me to the right direction?

Thanks,
Lily
<img width="765" alt="Screen Shot 2020-09-28 at 12 16 57 AM" src="https://user-images.githubusercontent.com/30990195/94402258-ac865c80-0120-11eb-9df6-3b7481e3fae1.png">

**Comment by ialja** [comment]
You should include it in the file where the `<head>` element is defined, usually it will be in `/_includes/head.html`. Just be sure to add it before the closing `</head>` tag.

**Comment by LilianYou** [comment]
Hi: Here is my html file which does not have <head> stage. Please see below. Is there any alternative solution? Thanks.

<img width="693" alt="Screen Shot 2020-10-16 at 3 03 41 AM" src="https://user-images.githubusercontent.com/30990195/96245467-34ab9500-0f5c-11eb-9a7b-2fae9d141ced.png">

**Comment by ashmaroli** [comment]
@LilianYou  What are the contents of `_includes/seo.html`?

**Comment by LilianYou** [comment]
Here it is. It comes with the template I think.

<img width="669" alt="Screen Shot 2020-10-16 at 3 57 25 AM" src="https://user-images.githubusercontent.com/30990195/96250450-b6eb8780-0f63-11eb-9186-11af47ea0a8c.png">

**Comment by ashmaroli** [comment]
Okay. So, your theme is already equipped to render metadata for SEO. But if you need the markup provided by this plugin
(`jekyll-seo-tag`), then simply replace the `{% include seo.html %}` at line 5 of `_includes/head.html` with `{% seo %}`:
```diff
- {% include seo.html %}
+ {% seo %}
```
