### ISSUE TITLE
locale in _config.yml ignored

### ISSUE THREAD

**Issue by phuhl** [jekyll/jekyll-seo-tag#420]
It seems to me, that `<meta property="og:locale" content="de" />` will always be set, based on `lang`, not on `locale`. At least for me.

My _config.yml includes this:

```yml
lang: de
locale: de_DE
```

I also tried:
locale: de-DE
locale: "de_DE"
locale: "de-DE"

**Comment by ashmaroli** [comment]
What version of this plugin are you using?

**Comment by phuhl** [comment]
jekyll-seo-tag (2.4.0)

**Comment by phuhl** [comment]
Jup, newest version is working fine. Sorry again.
