### ISSUE TITLE
Easy way to populate publisher info into JSON-LD

### ISSUE THREAD

**Issue by ain** [jekyll/jekyll-seo-tag#421]
Related to #332, I failed to find a way to populate `publisher` information into JSON-LD. 

`seo` YFM block does not seem to have the obvious way when following [Customising JSON-LD output](https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/advanced-usage.md#customizing-json-ld-output) guidelines, yet specs clearly refer to it as if it was available.

Please advise.

**Comment by hybridcattt** [comment]
I am researching the same issue at the moment. I found that `logo` has to be configured for publisher to be present:

> `logo` - URL to a site-wide logo (e.g., `/assets/your-company-logo.png`) - If you would like the "publisher" property
to be present, you must add this field to your site's configuration, during the validation of the structured data by
Google Search Console, if the `logo` field is not validated, you will find errors inherent to the publisher in the
[Rich Results Testing Tool](https://search.google.com/test/rich-results)

(from [Usage](https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md))
