### ISSUE TITLE
url, og:url, canonical_url are not work

### ISSUE THREAD

**Issue by 960813** [jekyll/jekyll-seo-tag#430]
https://github.com/jekyll/jekyll-seo-tag/blob/442133d89885bf59b8e31fc4b027956d56ba53b6/lib/jekyll-seo-tag/drop.rb#L188
https://github.com/jekyll/jekyll-seo-tag/blob/442133d89885bf59b8e31fc4b027956d56ba53b6/lib/jekyll-seo-tag/drop.rb#L176

The plugin is accessing page["canonical_url"] through the above two codes.

But my plugin only gets 'http://0.0.0.0:4000'.

The url property specified in _config.yml doesn't seem to work.

Why does this happen?

P.S - I use `jekyll serve`

**Comment by 960813** [comment]
additional: i use jekyll serve mode

**Comment by mwt** [comment]
Hi,

When you use `jekyll build` it should have the correct URL. Option `serve` uses localhost as the url in order to prevent complete links from breaking.

Best,

Matthew
