### ISSUE TITLE
Support for image paths relative to post

### ISSUE THREAD

**Issue by numist** [jekyll/jekyll-seo-tag#461]
My config uses [`permalink: /post/:year/:title/`](https://numi.st/post/2022/travel-uke/) together with [`jekyll-postfiles`](https://github.com/nhoizey/jekyll-postfiles) to keep assets local to their respective posts. This allows me to use simpler image tags in [my Markdown](https://github.com/numist/numi.st/blob/main/_posts/2022-04-21-travel-uke/2022-04-21-travel-uke.md) (`![…](image.jpg)`) when editing and as a consequence my post's images tend to be shipped to [`https://:url/post/:year/:title/image.jpg`](https://numi.st/post/2022/travel-uke/IMG_1232.jpeg).

Pre-#44, it was possible to specify `image: image.jpg` in the front matter and the generated URL would be relative to the post, but now `jekyll-seo` emits `https://:url/image.jpg`, which does not exist. #76 improved things somewhat by reintroducing the ability to link off-site images, but it's still not possible to use post-relative paths.

Obviously this can be worked around by specifying the fully expanded path (`image: /post/2022/cool-title/image.jpg`) in the front-matter, but this is brittle to reorganization (for example, when a post is moved from `_drafts` to `_posts`).

I think an ideal solution would allow domain-relative paths to be specified with a leading `/` (which is already consistent with [the documentation](https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md)) and post-relative paths to be specified without, but doing so would revert the behaviour described in #24 back to how it used to be—a second compatibility break.

So before investigating the code any further I wanted to know: what do people think about this?

**Comment by numist** [comment]
Alrighty, in the absence of opinions I'll draft a PR for this.

**Comment by donkirkby** [comment]
I just ran into this, and it sounds like you're planning three use cases for specifying a twitter image:

1. From some other site, specified as `https://example.com/project/post/path/to/image.png`.
2. Relative to this project's site, specified as `/post/path/to/image.png`.
3. Relative to this post, specified as `path/to/image.png`.

I looked at the [current code], and it seems to handle use cases 1 and 2 reasonably well. I guess you're going to add another conditional to handle case 3 when `raw_path` isn't absolute and doesn't start with `/`. Cases 1 and 3 will just use the `raw_path` as is, right?

For case 2, can I suggest that you switch to using `filters.relative_url`? With `filters.absolute_url`, I get `http://` with the default GitHub Pages configuration. I haven't found any actual problems with `http://`, but it makes me nervous.

[current code]: https://github.com/jekyll/jekyll-seo-tag/blob/master/lib/jekyll-seo-tag/image_drop.rb#L66-L70

**Comment by numist** [comment]
> I get http:// with the default GitHub Pages configuration. I haven't found any actual problems with http://, but it makes me nervous.

To be clear, you mean `absolute_url` is giving you `http://` but you want the URL to not include a scheme (or domain) so it will match the current page's (which presumably is `https://`)? That sounds like a separate issue but I'm happy to fold it in.

**Comment by numist** [comment]
The [opengraph spec](https://ogp.me/#url) is a bit ambiguous, but by the robustness principle my interpretation is that it's necessary to use `absolute_url`. Even if it's not, `absolute_url` [is a liquid filter](https://jekyllrb.com/docs/liquid/filters/) so it's probably worth taking up with the jekyll project if it's not giving you what you're expecting.

**Comment by numist** [comment]
Fixed by #466
