### ISSUE TITLE
link[@rel='me'] tag support

### ISSUE THREAD

**Issue by colindean** [jekyll/jekyll-seo-tag#485]
Would it be appropriate for this plugin to support the `link[@rel='me']` URL validation/verification ~standard that Mastodon and others are supporting to claim and verify an association between a profile and another URL?

I've implemented this in a Jekyll site but looking through our code, I wonder if that facility should be handled through this plugin. My current implementation is abstract, allowing the consumer to set `link_rel_me_urls` as a list of URL strings in `_config.yml` and it just emits those inside the appropriate tag inside the header.

I'm happy to put up a PR for this if it's the right plugin for that.

**Comment by Coedice** [comment]
I think this would be a useful addition. I would certainly use it for one.

**Comment by ashmaroli** [comment]
Hi, this ticket came to my notice just now.

From what I understand, `rel="me"` attribution is used for establishing equivalence between two user-profiles. i.e. John Doe would use this attribution to *interlink* their profile at URL `https://smp-1.com/users/john.doe` and `https://smp-2.org/u/johndoe789/` to indicate that the two profiles are of theirs. They may also use to interlink between two profiles on same platform e.g. `https://smp-1.com/users/john.doe` and `https://smp-1.com/users/jdoe123`.

In light of above, I fail to understand how `rel="me"` has relevance in meta tags for SEO. How is the plugin going to determine if current page (being indexed by crawler) is a legitimate equivalent of given user-profile. At that point what is the priority of `<link rel="me" ... />` on a page metadata over `<a rel="me" ...</a>` embedded in page content at anchor origin / destination (page being indexed)?

**Comment by Coedice** [comment]
I suppose that `<link rel="me" ... />` could be used as a social signal to search engines, since if you have a verified Mastodon account that has many followers, that would indicate that the website is likely to be a relevant result. Possibly, this could also boost the ranking of the Mastodon account, if the search engine has a high confidence of relevance of your website.

I have no idea if these things are _actually_ happening, but these are some ways this kind of tag could have an SEO impact.

**Comment by ashmaroli** [comment]
@Coedice, I understand SEO boost for an `About Me` page linked to a verified popular Mastodon profile but what is the relevance of this metadata on a page (in the same website) that is focused on something (not even remotely connected) to the Mastodon profile, say, a post glorifying a family recipe of handed down by the author's grandmother..? 😄

**Comment by Coedice** [comment]
the `<link rel="me" ... />` reflects the authorship/control of the two sources, so if they wrote an article about a family recipe, that actually _is_ related to their Mastodon account, by the fact that it is under their authorship/control.

A single website might link to different Mastodon accounts depending on the page, for example [https://mashable.com/author/aperry](https://mashable.com/author/aperry) and [https://mashable.com/author/stan-schroeder](https://mashable.com/author/stan-schroeder). They may want to even have their Mastodon accounts `<link rel="me" ... />`ed to from each of the articles they wrote. It would be great to be able to do this with the same `author` front matter object as is done for Twitter.

**Comment by ashmaroli** [comment]
> The `<link rel="me" ... />` reflects the authorship/control of the two sources..

I cannot find any reference supporting this statement, on the internet.
Either ways, this is not paramount to this plugin. I recommend adding the markup at the template level.

**Comment by benbalter** [comment]
Landed here via search hoping the plugin would "automatically" add the `link rel=me` tags [for mastadon verification](https://docs.joinmastodon.org/user/profile/#verification), similar to how we support specifying [social media profiles within the JSON-LD](https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md). Adding the additional source links here in case the discussion is revived at a later date.

> I recommend adding the markup at the template level.

:+1:. Easy enough to do.
