### ISSUE TITLE
Support Twitter summary card with large image

### ISSUE THREAD

**Issue by DirtyF** [jekyll/jekyll-seo-tag#68]
Hi,

Support of [large image in Twitter Summary Cards](https://dev.twitter.com/cards/types/summary-large-image) would be nice.

The only difference with the actual summary card seems to be the content attribute value:

```
<meta name="twitter:card" content="summary_large_image">
```
I manually added the meta:
https://github.com/sudweb/2016/blob/gh-pages/_includes/head.html#L8

I tested it on http://sudweb.github.io/2016/
It seems that if both twitter meta are present, Twitter use the large image version:

![twitter-card-summary-large](https://cloud.githubusercontent.com/assets/103008/13508494/85514c96-e187-11e5-958b-a65f26dd2ddd.png)

I can try to submit a PR if you agree adding this.

Thanks.

**Comment by benbalter** [comment]
What do you think about using `summary_large_image` whenever `post.image` is defined?

**Comment by DirtyF** [comment]
`post.image` or `page.image` in my above case would be great.

**Comment by benbalter** [comment]
Ahh yes, `page.image`. @DirtyF if you'd like to submit a pull request to change https://github.com/jekyll/jekyll-seo-tag/blob/master/lib/template.html#L127 `if page.image` that'd be awesome!

**Comment by ashchan** [comment]
As I understand Twitter Card, `summary_large_image` is for displaying a large image, while `summary` is for no image or thumbnail. When a page does have an image and wants to show that image as thumbnail for the card, it's not supported now.

Would anyone like to specify to use `summary_large_image` or `summary` so s/he can choose how the card is showing (I would like that feature)?

**Comment by DirtyF** [comment]
@ashchan yep, we should support both, expect some PR soon : https://github.com/jekyll/jekyll-seo-tag/issues/84

**Comment by ashchan** [comment]
@DirtyF That's awesome! Thanks!
