### ISSUE TITLE
Add support for a global image if one isn't specified per post/page

### ISSUE THREAD

**Issue by XhmikosR** [jekyll/jekyll-seo-tag#7]
Otherwise, there is no image shown and it doesn't look very nice.

While at it, perhaps you could handle `og:image:secure_url` too when the `url` is https. I personally do this https://github.com/mpc-hc/mpc-hc.org/blob/master/source/_includes/header.html#L39

Finally, I wonder if it would be possible to add the width and height too automatically?

**Comment by benbalter** [comment]
> Add support for a global image if one isn't specified per post/page

If I'm understanding correctly, this can be done via frontmatter defaults.

> add the width and height too automatically?

Not within Jekyll (we'd have to add Ruby to read the image, which I'd prefer not to do for purposes of keeping things simple).

**Comment by XhmikosR** [comment]
IMO the global image seems reasonable since it's SEO specific. I can add it manually, sure, I'm just looking what things are missing from my implementation before switching to this.

**Comment by pathawks** [comment]
Frontmatter defaults are the way to go :+1:
