### ISSUE TITLE
Strip html from meta property

### ISSUE THREAD

**Issue by iloveip** [jekyll/jekyll-seo-tag#73]
Hi there,

Is there anyway to strip html from meta property like `og:title`, `og:description` and so on? I have some html code in my output like `&nbsp;` and would like to remove it.

**Comment by benbalter** [comment]
@iloveip this should [already be the case](https://github.com/jekyll/jekyll-seo-tag/blob/master/lib/template.html#L49). Is it just &nbsp; or are you able to recreate it with other HTML markup?

**Comment by iloveip** [comment]
@benbalter in meta property `og:title` and `og:description` it's just `&nbsp;`. In `<script type="application/ld+json">` there are some other tags as well:

```
<script type="application/ld+json">
    {
      "@context": "http://schema.org",
      "@type": "NewsArticle",
      "headline": "Book <em>of</em>&nbsp;records",
      "image": null,
      "datePublished": "2016-03-01T00:00:00+03:00",
      "description": ""
    }
  </script> 
```
There are also `&nbsp;` tags in `<link rel="next">` and `<link rel="prev">`.

**Comment by pathawks** [comment]
We are [stripping HTML](https://github.com/jekyll/jekyll-seo-tag/blob/master/lib/template.html#L49), so I’m not sure how the `<em>` tag slipped through. Would *love* a PR with a failing test to try to fix that one.

As far as `&nbsp;`, this is totally valid inside a title or description. We shouldn’t try to modify these.
