### ISSUE TITLE
Extra slashes in logo output

### ISSUE THREAD

**Issue by iloveip** [jekyll/jekyll-seo-tag#74]
Hi there,

In my `_config.yml` file I have:
```
# Setup
url: http://www.iloveip.ru/
logo: /images/logo_XL.png
```

But in the output for logo there are some extra slashes:
```
<script type="application/ld+json">
    {
      "@context": "http://schema.org",
      "@type": "Organization",
      "url": "http://www.iloveip.ru/",
      "logo": "http://www.iloveip.ru///images/logo_XL.png"
    }
  </script>
```

Is there any way to fix it?

**Comment by benbalter** [comment]
@iloveip thanks for the issue. I suspect this will be fixed by https://github.com/jekyll/jekyll-seo-tag/pull/60 in the next release. Also to note, your `site.url` should not have a trailing slash and `baseurl` should not be `/`, if it is (which I suspect may also be the case).

**Comment by benbalter** [comment]
Please leave a comment here if it's not fixed in the next version of the plugin. :smile:
