### ISSUE TITLE
The Whole Content is Put in `<meta name="twitter:description"...` and the like when `description` is not present

### ISSUE THREAD

**Issue by ickc** [jekyll/jekyll-seo-tag#75]
Hi,

I found out that if the post do not have a metadata of `description` in the YAML front matter, the `jekyll-seo-tag` will put the whole content of the document in the `<meta name="twitter:description"...`, causing a huge resultant file.

**Comment by boturnbow** [comment]
The current version of the seo tag does not output a tag like `<meta name="twitter:description"...`

Instead it outputs `<meta property="og:description" content="...">` and `"description": "..."` in the LD+JSON block. Could the results you are seeing be coming from a layout and not from the seo tag? Do you have some code I could look at?

I notice that the seo tag uses page.excerpt if page.description is not present. Maybe that's what you are seeing?

**Comment by boturnbow** [comment]
FYI: http://jekyllrb.com/docs/posts/#post-excerpts

**Comment by ickc** [comment]
Hi, thanks for explaining it. I am very busy in these 2 weeks and will come back after that. I'll make a MWE to see what's wrong and report my finding.

**Comment by pathawks** [comment]
This plugin does not output any `twitter:description` tag.

We [_do_ output `og:description`](https://github.com/jekyll/jekyll-seo-tag/blob/v1.3.3/lib/template.html#L103-L106). We try to pull that value from `page.description`. If the post metadata does not include `description`, we fallback [first to `page.excerpt` and then to `site.description`](https://github.com/jekyll/jekyll-seo-tag/blob/v1.3.3/lib/template.html#L52).

I am going to close this for now, but please do reopen if you find a case where we are dumping the whole page into a `meta` tag; nobody wants that.
