### ISSUE TITLE
Prev/next links are more appropriate for pagination?

### ISSUE THREAD

**Issue by neoascetic** [jekyll/jekyll-seo-tag#80]
Quote from [this google blogpost](https://webmasters.googleblog.com/2011/09/pagination-with-relnext-and-relprev.html):

> Throughout the web, a paginated series of content may take many shapes—it can be an article divided into several component pages, or a product category with items spread across several pages, or a forum thread divided into a sequence of URLs. 

I am not sure that it is good to use prev/next meta links on posts because content on each of them may be completely different and not related at all. However, I am sure that these links must be enabled on pages with pagination. What do you think?

**Comment by tfe** [comment]
@neoascetic I'm in agreement on this and wanted to use it this way in my own project, so I made a branch to do it that way. Feel free to use it if you like: https://github.com/jekyll/jekyll-seo-tag/pull/87.
