### ISSUE TITLE
Question about Google Analytics

### ISSUE THREAD

**Issue by iloveip** [jekyll/jekyll-seo-tag#82]
Hi there,

I see that jekyll-seo-tag generates `<script async="" src="//www.google-analytics.com/analytics.js"></script>` in the `<head>` of the site. Do I need to include the standard Google Analytics script to the site additionally? If not, how do I add Google Analytics ID code (UA-XXXXXXXX-X) to the script above?

**Comment by DirtyF** [comment]
@iloveip AFAIK  jekyll-seo-tag does not insert any analytics script, maybe you use another Jekyll plugin? The best place to to specify your GA tracking ID is the `_config.yml` file.

**Comment by iloveip** [comment]
@DirtyF Thank you very much for your reply. But I get this code inside Jekyll SEO tag. Here is the full version (some text is in Russian):

```
<!-- Begin Jekyll SEO tag v1.3.3 -->
<meta property="og:title" content="Отчётность по УСН за 2015 год">
<meta name="description" content="Всё для самостоятельной регистрации ИП и ведения бизнеса">
<meta property="og:description" content="Всё для самостоятельной регистрации ИП и ведения бизнеса">
<link rel="canonical" href="http://www.iloveip.ru/">
<meta property="og:url" content="http://www.iloveip.ru/">
<meta property="og:site_name" content="Я люблю ИП">
<meta property="og:image" content="http://www.iloveip.ru/assets/logo.png">
<script async="" src="//www.google-analytics.com/analytics.js"></script>
<script type="application/ld+json">
  {
    "@context": "http://schema.org",
    "@type": "WebSite",
    "name": "Я люблю ИП",
    "headline": "Отчётность по УСН за 2015 год",
    "image": "http://www.iloveip.ru/assets/logo.png",
    "description": "Всё для самостоятельной регистрации ИП и ведения бизнеса",
    "logo": "http://www.iloveip.ru/assets/logo.png",
    "sameAs": "https://vk.com/iloveip, https://www.facebook.com/iloveip.ru/",
    "url": "http://www.iloveip.ru/"
  }
</script>
<!-- End Jekyll SEO tag -->
```

**Comment by DirtyF** [comment]
@iloveip Weird, I can't see [any reference to analytics in jekyll-seo-tag source code](https://github.com/jekyll/jekyll-seo-tag/search?utf8=%E2%9C%93&q=analytics), and I can't reproduce your issue.

```
<!-- Begin Jekyll SEO tag v1.3.3 -->
<title>Jekyll-fr - Communauté francophone des utilisateurs de Jekyll</title>
<meta property="og:title" content="Jekyll-fr">
<meta name="description" content="Communauté francophone des utilisateurs de Jekyll">
<meta property="og:description" content="Communauté francophone des utilisateurs de Jekyll">
<link rel="canonical" href="http://jekyll-fr.org/">
<meta property="og:url" content="http://jekyll-fr.org/">
<meta property="og:site_name" content="Jekyll-fr">
<meta name="twitter:card" content="summary">
<meta name="twitter:site" content="@jekyll_fr">
<script type="application/ld+json">
  {
    "@context": "http://schema.org",
    "@type": "WebSite",
    "name": "Jekyll-fr",
    "headline": "Jekyll-fr",
    "description": "Communauté francophone des utilisateurs de Jekyll",
    "sameAs": ["https://twitter.com/jekyll_fr","https://github.com/jekyll-fr"],
    "url": "http://jekyll-fr.org/"
  }
</script>
<!-- End Jekyll SEO tag -->
```

**Comment by benbalter** [comment]
Do you have another plugin or template that's doing some sort of find/replace on `<script>`? Can you reproduce this with another site?

**Comment by pathawks** [comment]
> @pathawks what do you think about supporting analytics tag in seo-tag?

Feels out of scope. Analytics is not SEO.

Perhaps not a bad idea for another micro plugin, but it feels to me like it would not belong _here_.

**Comment by iloveip** [comment]
I guess this tag is generated by Google Analytics itself. I don't know why it put it inside Jekyll SEO tag. Sorry for the trouble and thank you very much for your help.

**Comment by jhabdas** [comment]
FWIW, and though not related to this gem, I also saw this behavior using the GA async template and the following code:

```liquid
{% if jekyll.environment == 'production' and site.google_analytics_key != '' %}
	<script>
		(function(i,s,o,g,r,a,m){i["GoogleAnalyticsObject"]=r;i[r]=i[r]||function(){
		(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,"script","//www.google-analytics.com/analytics.js","ga");

		ga("create", "{{ site.google_analytics_key }}", "auto");
		ga("send", "pageview");
	</script>
{% endif %}
```

Note this is occurring because the async tag creates a [Script DOM Element](https://www.stevesouders.com/blog/2009/04/27/loading-scripts-without-blocking/) in the head and simply chooses to plop itself in between the Jekyll SEO Tag gem comment block. :)~

<img width="447" alt="screen shot 2017-01-15 at 11 20 15 am" src="https://cloud.githubusercontent.com/assets/440298/21960020/e9cbe5dc-db14-11e6-9de7-85ec29bdb9be.png">

**Comment by pathawks** [comment]
So it's in the DOM but not the generated HTML?
That makes a lot more sense. I'm sure the async loader just puts it above any existing `<script>` tags, which means right before our JSON-LD data.

**Comment by jhabdas** [comment]
Aye aye, sir
