### ISSUE TITLE
Attempted Frozen Title Change

### ISSUE THREAD

**Issue by XhmikosR** [jekyll/jekyll-seo-tag#83]
@pathawks: I never said the site doesn't build. I said the Facebook debugger throws that error.

https://github.com/jekyll/jekyll-seo-tag/issues/10#issuecomment-217445889

```
Attempted Frozen Title Change
It appears that you are trying to change the property og:title from Home · MPC-HC to Home. If so, you are not allowed to for this object because too many actions have been published against it.
```

I'm using the plugin as `{% seo title=false %}`. https://github.com/mpc-hc/mpc-hc.org/compare/jekyll-seo-tag

**Comment by pathawks** [comment]
How can I recreate this error?

**Comment by XhmikosR** [comment]
Not sure if there is any debugger which accepts HTML upload. If that worked you could copy the local HTML.

Otherwise, I can upload the files for a few min and see the report from https://developers.facebook.com/tools/debug/sharing/

**Comment by XhmikosR** [comment]
Do you want me to upload the files from that branch to the live server to
see the issue?

Another thing I noticed is that the twitter author is set as the post
author. This isn't the case for me since we only have an organization
account. How can I override it in config without adding new properties in
each post?

**Comment by pathawks** [comment]
It seems like (from various unofficial sources) after a page has been public for some time or after it has a certain number of likes, Facebook freezes some of its info about the page and will not allow for any changes. If _that_ is what you are running into, I am not sure there is anything that we can do to fix that.

> Another thing I noticed is that the twitter author is set as the post author.

That's a separate issue.

**Comment by XhmikosR** [comment]
I'm gonna give it another go later today or tomorrow and let you know.

Do you have any link for what you said above about FB freezing the title?

**Comment by pathawks** [comment]
http://stackoverflow.com/a/26252936

**Comment by XhmikosR** [comment]
All right, thanks. I'm gonna close this and try to contact them when I make the switch to jekyll-seo-tag.
