### ISSUE TITLE
Add Config to Prevent Site Name from Being appended to Title

### ISSUE THREAD

**Issue by jaypeedevlin** [jekyll/jekyll-seo-tag#88]
It would be fantastic to have something in config that would prevent this.

Currently if `site.title` is absent it has a fallback to `site.name` - removing both breaks a lot of other functionality.

It would be great to be able to have the meta title tag be `post.title` without `- bar` on the end - is this possible to add?

(if only I had a better understanding of ruby I would fork and PR this myself)

**Comment by pathawks** [comment]
Are you referring to the `<title>` tag?

If so, you can [disable its output entirely](https://github.com/jekyll/jekyll-seo-tag#disabling-title-output) and specify your own `title` in your template 👍

**Comment by jaypeedevlin** [comment]
Yes I am - I thought it might be nice to include an option to drop the appending - if there's not a view to do that I'll just use `title=false` as suggested and recreate the logic in my layout - thanks :)
