### ISSUE TITLE
Define image (og:image) globally in _config.yml or layouts

### ISSUE THREAD

**Issue by renshuki** [jekyll/jekyll-seo-tag#95]
Hi,
Actually **image:** need to be specified in a (post/page/document) YAML front matter. It would be nice if this parameter could be added globally to the `_config.yml` file (with the possibility to overwrite it afterwards via YAML front matter if needed).

**Comment by pathawks** [comment]
The good news is Jekyll already supports this :+1:

See [Front Matter defaults](https://jekyllrb.com/docs/configuration/#front-matter-defaults)

**Comment by renshuki** [comment]
OK my bad... Thank you for the help! ;)
