### ISSUE TITLE
idea: SEO/SMO linter

### ISSUE THREAD

**Issue by stereobooster** [jekyll/jekyll-seo-tag#99]
Imagine linter for checking SEO/SMO tags in frontmatter.
Something like:

```
jekyll lint-seo-tags
  _posts/2016-07-02-my-post.md
    title too long: use 50 chars max
    no description and no excerpt
    image ratio for facebook inappropriate, expecting 2:1
    image size for twitter too big, expecting not more than 2mb
```

**Comment by pathawks** [comment]
Is `jekyll doctor` plugable? I like this idea, just not on every build 👍🏼

**Comment by benbalter** [comment]
See https://github.com/jekyll/jekyll-seo-tag#what-it-doesnt-do.

**Comment by stereobooster** [comment]
I started project [jekyll-seo-lint](https://github.com/stereobooster/jekyll-seo-lint), which is not working yet, and not sure how long it will take (no promises here).

### Here is how I see jekyll SEO/SMO ecosystem

[jekyll-seo-tag](https://github.com/jekyll/jekyll-seo-tag) - Jekyll plugin to add metadata tags for search engines and social networks to better index and display your site's content.

[jekyll-seo-lint](https://github.com/stereobooster/jekyll-seo-lint) - Jekyll plugin to validate metadata provided in front matter and in configuration. It validates if data is in appropriate format for `jekyll-seo-tag` and in some extent if it is appropriate format. Yet it can not guaranty full-validation. For full validation use official validation tools.

[jekyll-seo-gem](https://github.com/pmarsceill/jekyll-seo-gem) - A script to help with seo on jekyll blog posts. `jekyll-seo-lint` validates front matter, while this script generates HTML and validates it.

**Comment by pathawks** [comment]
I agree that any SEO advice is out of scope for this plugin. I was thinking of this only as a sanity check to make sure that any required properties were provided.
